### ISSUE TITLE
"Input source audio" setting doesn't match the names of input devices on my system

### ISSUE THREAD

**Issue by nekohayo** [iacopodeenosee/EasyScreenCast#25] opened 2015-06-19 02:35 UTC
On my system I have a bunch of devices (motherboard's analog in/out, USB microphone, and graphic card's HDMI output), most of which are disabled in pavucontrol so that I can have only the USB microphone, and the analog output from the motherboard.

* EasyScreenCast's "Input source Audio" setting lists my current devices by their type, instead of their true name. So in my case it says "analog-output-lineout" and "analog-input-mic" instead of "Monitor of Internal surround 5.1 analogic audio" and "AK5370 I/F A/D Converter" (that's how my microphone calls itself)...
* There should probably also be an option (the default) in the combobox called "Default device (name_of_device)"

**Comment by iacopodeenosee** [comment] 2015-06-19 19:59
if think this is a duplicate of #17 , i use GVC to extract the list of audio source, the problem is that some descriptions are identical even if they refer to different ports and It can generate a lot of confusion, to solve the problem I want to create an UI that allows me to see all available information of source, like description, port, card and name.

**Closed** 2015-10-17 10:16 UTC
Labels: duplicate
